version: '3'
services:
  app:
    build:
      args:
        - NODE_VER=20.10.0
      context: .
      dockerfile: Dockerfile
    container_name: yutaro-kashiwa
    tty: true
    volumes:
      - ./app:/data
    ports:
      - "3000:3000"
      - "8080:8080"